//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace HANGE.Media.Entity
{
	/// <summary>
	/// 实体类Pe_device。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pe_device")]
	[Serializable]
	
	public partial class Pe_device : Dos.ORM.Entity
	{
		#region Model
		private int _Id;
		private string _Hostname;
		private string _Hostcode;
		private string _Hostbody;
		private string _Groupcode;
		private string _Danwei;
		private int? _Fsec;
		private string _Creater;
		private string _Creatertime;
		private string _Moder;
		private string _Modtime;
		private string _State;
		private string _Product_name;
		private string _Product_firm;
		private int? _Capacity;
		private int? _Last_login;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		
		public int Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 机主名
		/// </summary>
		[Field("hostname")]
		
		public string Hostname
		{
			get { return _Hostname; }
			set
			{
				this.OnPropertyValueChange("Hostname");
				this._Hostname = value;
			}
		}
		/// <summary>
		/// 机主编号
		/// </summary>
		[Field("hostcode")]
		
		public string Hostcode
		{
			get { return _Hostcode; }
			set
			{
				this.OnPropertyValueChange("Hostcode");
				this._Hostcode = value;
			}
		}
		/// <summary>
		/// 机身编号
		/// </summary>
		[Field("hostbody")]
		
		public string Hostbody
		{
			get { return _Hostbody; }
			set
			{
				this.OnPropertyValueChange("Hostbody");
				this._Hostbody = value;
			}
		}
		/// <summary>
		/// 所在群号
		/// </summary>
		[Field("groupcode")]
		
		public string Groupcode
		{
			get { return _Groupcode; }
			set
			{
				this.OnPropertyValueChange("Groupcode");
				this._Groupcode = value;
			}
		}
		/// <summary>
		/// 所在单位
		/// </summary>
		[Field("danwei")]
		
		public string Danwei
		{
			get { return _Danwei; }
			set
			{
				this.OnPropertyValueChange("Danwei");
				this._Danwei = value;
			}
		}
		/// <summary>
		/// 媒体文件缩略图截取秒数
		/// </summary>
		[Field("fsec")]
		
		public int? Fsec
		{
			get { return _Fsec; }
			set
			{
				this.OnPropertyValueChange("Fsec");
				this._Fsec = value;
			}
		}
		/// <summary>
		/// 创建人
		/// </summary>
		[Field("creater")]
		
		public string Creater
		{
			get { return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("creatertime")]
		
		public string Creatertime
		{
			get { return _Creatertime; }
			set
			{
				this.OnPropertyValueChange("Creatertime");
				this._Creatertime = value;
			}
		}
		/// <summary>
		/// 修改人
		/// </summary>
		[Field("moder")]
		
		public string Moder
		{
			get { return _Moder; }
			set
			{
				this.OnPropertyValueChange("Moder");
				this._Moder = value;
			}
		}
		/// <summary>
		/// 修改时间
		/// </summary>
		[Field("modtime")]
		
		public string Modtime
		{
			get { return _Modtime; }
			set
			{
				this.OnPropertyValueChange("Modtime");
				this._Modtime = value;
			}
		}
		/// <summary>
		/// _0-正常；1-报障，2-报废；
		/// </summary>
		[Field("state")]
		
		public string State
		{
			get { return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 产品名称
		/// </summary>
		[Field("product_name")]
		
		public string Product_name
		{
			get { return _Product_name; }
			set
			{
				this.OnPropertyValueChange("Product_name");
				this._Product_name = value;
			}
		}
		/// <summary>
		/// 厂商
		/// </summary>
		[Field("product_firm")]
		
		public string Product_firm
		{
			get { return _Product_firm; }
			set
			{
				this.OnPropertyValueChange("Product_firm");
				this._Product_firm = value;
			}
		}
		/// <summary>
		/// 容量（MB）
		/// </summary>
		[Field("capacity")]
		
		public int? Capacity
		{
			get { return _Capacity; }
			set
			{
				this.OnPropertyValueChange("Capacity");
				this._Capacity = value;
			}
		}
		/// <summary>
		/// 上次使用时间
		/// </summary>
		[Field("last_login")]
		
		public int? Last_login
		{
			get { return _Last_login; }
			set
			{
				this.OnPropertyValueChange("Last_login");
				this._Last_login = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Hostname,
				_.Hostcode,
				_.Hostbody,
				_.Groupcode,
				_.Danwei,
				_.Fsec,
				_.Creater,
				_.Creatertime,
				_.Moder,
				_.Modtime,
				_.State,
				_.Product_name,
				_.Product_firm,
				_.Capacity,
				_.Last_login,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Hostname,
				this._Hostcode,
				this._Hostbody,
				this._Groupcode,
				this._Danwei,
				this._Fsec,
				this._Creater,
				this._Creatertime,
				this._Moder,
				this._Modtime,
				this._State,
				this._Product_name,
				this._Product_firm,
				this._Capacity,
				this._Last_login,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pe_device");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id", "pe_device", "");
			/// <summary>
			/// 机主名
			/// </summary>
			public readonly static Field Hostname = new Field("hostname", "pe_device", "机主名");
			/// <summary>
			/// 机主编号
			/// </summary>
			public readonly static Field Hostcode = new Field("hostcode", "pe_device", "机主编号");
			/// <summary>
			/// 机身编号
			/// </summary>
			public readonly static Field Hostbody = new Field("hostbody", "pe_device", "机身编号");
			/// <summary>
			/// 所在群号
			/// </summary>
			public readonly static Field Groupcode = new Field("groupcode", "pe_device", "所在群号");
			/// <summary>
			/// 所在单位
			/// </summary>
			public readonly static Field Danwei = new Field("danwei", "pe_device", "所在单位");
			/// <summary>
			/// 媒体文件缩略图截取秒数
			/// </summary>
			public readonly static Field Fsec = new Field("fsec", "pe_device", "媒体文件缩略图截取秒数");
			/// <summary>
			/// 创建人
			/// </summary>
			public readonly static Field Creater = new Field("creater", "pe_device", "创建人");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field Creatertime = new Field("creatertime", "pe_device", "创建时间");
			/// <summary>
			/// 修改人
			/// </summary>
			public readonly static Field Moder = new Field("moder", "pe_device", "修改人");
			/// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field Modtime = new Field("modtime", "pe_device", "修改时间");
			/// <summary>
			/// _0-正常；1-报障，2-报废；
			/// </summary>
			public readonly static Field State = new Field("state", "pe_device", "_0-正常；1-报障，2-报废；");
			/// <summary>
			/// 产品名称
			/// </summary>
			public readonly static Field Product_name = new Field("product_name", "pe_device", "产品名称");
			/// <summary>
			/// 厂商
			/// </summary>
			public readonly static Field Product_firm = new Field("product_firm", "pe_device", "厂商");
			/// <summary>
			/// 容量（MB）
			/// </summary>
			public readonly static Field Capacity = new Field("capacity", "pe_device", "容量（MB）");
			/// <summary>
			/// 上次使用时间
			/// </summary>
			public readonly static Field Last_login = new Field("last_login", "pe_device", "上次使用时间");
		}
		#endregion
	}
}