//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;
using Dos.ORM.MySql;

namespace HANGE.Media.Entity
{
	/// <summary>
	/// 实体类Pe_danwei。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pe_danwei")]
	[Serializable]
	
	public partial class Pe_danwei : Dos.ORM.Entity
	{
		#region Model
		private int _Id;
		private string _Bh;
		private string _Dname;
		private string _Note;
		private string _Creater;
		private int? _Createtime;
		private string _Moder;
		private int? _Modtime;
		private int _Parentid;
		private int? _Orderby;
		private string _Unitsyscode;

		/// <summary>
		/// 
		/// </summary>
		[Field("id")]
		
		public int Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 单位编号
		/// </summary>
		[Field("bh")]
		
		public string Bh
		{
			get { return _Bh; }
			set
			{
				this.OnPropertyValueChange("Bh");
				this._Bh = value;
			}
		}
		/// <summary>
		/// 单位名称
		/// </summary>
		[Field("dname")]
		
		public string Dname
		{
			get { return _Dname; }
			set
			{
				this.OnPropertyValueChange("Dname");
				this._Dname = value;
			}
		}
		/// <summary>
		/// 单位备注
		/// </summary>
		[Field("note")]
		
		public string Note
		{
			get { return _Note; }
			set
			{
				this.OnPropertyValueChange("Note");
				this._Note = value;
			}
		}
		/// <summary>
		/// 创建人
		/// </summary>
		[Field("creater")]
		
		public string Creater
		{
			get { return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("createtime")]
		
		public int? Createtime
		{
			get { return _Createtime; }
			set
			{
				this.OnPropertyValueChange("Createtime");
				this._Createtime = value;
			}
		}
		/// <summary>
		/// 修改人
		/// </summary>
		[Field("moder")]
		
		public string Moder
		{
			get { return _Moder; }
			set
			{
				this.OnPropertyValueChange("Moder");
				this._Moder = value;
			}
		}
		/// <summary>
		/// 修改时间
		/// </summary>
		[Field("modtime")]
		
		public int? Modtime
		{
			get { return _Modtime; }
			set
			{
				this.OnPropertyValueChange("Modtime");
				this._Modtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("parentid")]
		
		public int Parentid
		{
			get { return _Parentid; }
			set
			{
				this.OnPropertyValueChange("Parentid");
				this._Parentid = value;
			}
		}
		/// <summary>
		/// 单位排序
		/// </summary>
		[Field("orderby")]
		
		public int? Orderby
		{
			get { return _Orderby; }
			set
			{
				this.OnPropertyValueChange("Orderby");
				this._Orderby = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("unitsyscode")]
		
		public string Unitsyscode
		{
			get { return _Unitsyscode; }
			set
			{
				this.OnPropertyValueChange("Unitsyscode");
				this._Unitsyscode = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Bh,
				_.Dname,
				_.Note,
				_.Creater,
				_.Createtime,
				_.Moder,
				_.Modtime,
				_.Parentid,
				_.Orderby,
				_.Unitsyscode,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Bh,
				this._Dname,
				this._Note,
				this._Creater,
				this._Createtime,
				this._Moder,
				this._Modtime,
				this._Parentid,
				this._Orderby,
				this._Unitsyscode,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pe_danwei");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id", "pe_danwei", "");
			/// <summary>
			/// 单位编号
			/// </summary>
			public readonly static Field Bh = new Field("bh", "pe_danwei", "单位编号");
			/// <summary>
			/// 单位名称
			/// </summary>
			public readonly static Field Dname = new Field("dname", "pe_danwei", "单位名称");
			/// <summary>
			/// 单位备注
			/// </summary>
			public readonly static Field Note = new Field("note", "pe_danwei", "单位备注");
			/// <summary>
			/// 创建人
			/// </summary>
			public readonly static Field Creater = new Field("creater", "pe_danwei", "创建人");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field Createtime = new Field("createtime", "pe_danwei", "创建时间");
			/// <summary>
			/// 修改人
			/// </summary>
			public readonly static Field Moder = new Field("moder", "pe_danwei", "修改人");
			/// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field Modtime = new Field("modtime", "pe_danwei", "修改时间");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Parentid = new Field("parentid", "pe_danwei", "");
			/// <summary>
			/// 单位排序
			/// </summary>
			public readonly static Field Orderby = new Field("orderby", "pe_danwei", "单位排序");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Unitsyscode = new Field("unitsyscode", "pe_danwei", "");
		}
		#endregion
	}
}