//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace HANGE.Media.Entity
{
	/// <summary>
	/// 实体类Pe_serverinfo。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("pe_serverinfo")]
	[Serializable]
	
	public partial class Pe_serverinfo : Dos.ORM.Entity
	{
		#region Model
		private int _Id;
		private string _Servername;
		private string _Serverip;
		private string _Ftpusername;
		private string _Pwd;
		private int? _Port;
		private string _Path;
		private int? _Flag;
		private string _Disk_free_space;
		private string _Creater;
		private string _Creatertime;
		private string _Moder;
		private string _Modtime;

		/// <summary>
		/// FTP服务地址表
		/// </summary>
		[Field("id")]
		
		public int Id
		{
			get { return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 服务器名称
		/// </summary>
		[Field("servername")]
		
		public string Servername
		{
			get { return _Servername; }
			set
			{
				this.OnPropertyValueChange("Servername");
				this._Servername = value;
			}
		}
		/// <summary>
		/// 服务器ip地址
		/// </summary>
		[Field("serverip")]
		
		public string Serverip
		{
			get { return _Serverip; }
			set
			{
				this.OnPropertyValueChange("Serverip");
				this._Serverip = value;
			}
		}
		/// <summary>
		/// 登录名
		/// </summary>
		[Field("ftpusername")]
		
		public string Ftpusername
		{
			get { return _Ftpusername; }
			set
			{
				this.OnPropertyValueChange("Ftpusername");
				this._Ftpusername = value;
			}
		}
		/// <summary>
		/// 密码
		/// </summary>
		[Field("pwd")]
		
		public string Pwd
		{
			get { return _Pwd; }
			set
			{
				this.OnPropertyValueChange("Pwd");
				this._Pwd = value;
			}
		}
		/// <summary>
		/// 端口
		/// </summary>
		[Field("port")]
		
		public int? Port
		{
			get { return _Port; }
			set
			{
				this.OnPropertyValueChange("Port");
				this._Port = value;
			}
		}
		/// <summary>
		/// 路径
		/// </summary>
		[Field("path")]
		
		public string Path
		{
			get { return _Path; }
			set
			{
				this.OnPropertyValueChange("Path");
				this._Path = value;
			}
		}
		/// <summary>
		/// 使用标志 0-未使用 1-使用
		/// </summary>
		[Field("flag")]
		
		public int? Flag
		{
			get { return _Flag; }
			set
			{
				this.OnPropertyValueChange("Flag");
				this._Flag = value;
			}
		}
		/// <summary>
		/// 目录中的可用空间
		/// </summary>
		[Field("disk_free_space")]
		
		public string Disk_free_space
		{
			get { return _Disk_free_space; }
			set
			{
				this.OnPropertyValueChange("Disk_free_space");
				this._Disk_free_space = value;
			}
		}
		/// <summary>
		/// 创建人
		/// </summary>
		[Field("creater")]
		
		public string Creater
		{
			get { return _Creater; }
			set
			{
				this.OnPropertyValueChange("Creater");
				this._Creater = value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		[Field("creatertime")]
		
		public string Creatertime
		{
			get { return _Creatertime; }
			set
			{
				this.OnPropertyValueChange("Creatertime");
				this._Creatertime = value;
			}
		}
		/// <summary>
		/// 修改人
		/// </summary>
		[Field("moder")]
		
		public string Moder
		{
			get { return _Moder; }
			set
			{
				this.OnPropertyValueChange("Moder");
				this._Moder = value;
			}
		}
		/// <summary>
		/// 改修时间
		/// </summary>
		[Field("modtime")]
		
		public string Modtime
		{
			get { return _Modtime; }
			set
			{
				this.OnPropertyValueChange("Modtime");
				this._Modtime = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id,
			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Servername,
				_.Serverip,
				_.Ftpusername,
				_.Pwd,
				_.Port,
				_.Path,
				_.Flag,
				_.Disk_free_space,
				_.Creater,
				_.Creatertime,
				_.Moder,
				_.Modtime,
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Servername,
				this._Serverip,
				this._Ftpusername,
				this._Pwd,
				this._Port,
				this._Path,
				this._Flag,
				this._Disk_free_space,
				this._Creater,
				this._Creatertime,
				this._Moder,
				this._Modtime,
			};
		}
		/// <summary>
		/// 是否是v1.10.5.6及以上版本实体。
		/// </summary>
		/// <returns></returns>
		public override bool V1_10_5_6_Plus()
		{
			return true;
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "pe_serverinfo");
			/// <summary>
			/// FTP服务地址表
			/// </summary>
			public readonly static Field Id = new Field("id", "pe_serverinfo", "FTP服务地址表");
			/// <summary>
			/// 服务器名称
			/// </summary>
			public readonly static Field Servername = new Field("servername", "pe_serverinfo", "服务器名称");
			/// <summary>
			/// 服务器ip地址
			/// </summary>
			public readonly static Field Serverip = new Field("serverip", "pe_serverinfo", "服务器ip地址");
			/// <summary>
			/// 登录名
			/// </summary>
			public readonly static Field Ftpusername = new Field("ftpusername", "pe_serverinfo", "登录名");
			/// <summary>
			/// 密码
			/// </summary>
			public readonly static Field Pwd = new Field("pwd", "pe_serverinfo", "密码");
			/// <summary>
			/// 端口
			/// </summary>
			public readonly static Field Port = new Field("port", "pe_serverinfo", "端口");
			/// <summary>
			/// 路径
			/// </summary>
			public readonly static Field Path = new Field("path", "pe_serverinfo", "路径");
			/// <summary>
			/// 使用标志 0-未使用 1-使用
			/// </summary>
			public readonly static Field Flag = new Field("flag", "pe_serverinfo", "使用标志 0-未使用 1-使用");
			/// <summary>
			/// 目录中的可用空间
			/// </summary>
			public readonly static Field Disk_free_space = new Field("disk_free_space", "pe_serverinfo", "目录中的可用空间");
			/// <summary>
			/// 创建人
			/// </summary>
			public readonly static Field Creater = new Field("creater", "pe_serverinfo", "创建人");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field Creatertime = new Field("creatertime", "pe_serverinfo", "创建时间");
			/// <summary>
			/// 修改人
			/// </summary>
			public readonly static Field Moder = new Field("moder", "pe_serverinfo", "修改人");
			/// <summary>
			/// 改修时间
			/// </summary>
			public readonly static Field Modtime = new Field("modtime", "pe_serverinfo", "改修时间");
		}
		#endregion
	}
}